### ISSUE TITLE
Unable to start the webpack server

### ISSUE THREAD

**Issue by yann510** [swimlane/angular2-data-table#190]
I'm submitting a 
[X] bug report

**Current behavior**
Getting error when doing `npm start`

**Expected behavior**
I expect the webpack server to run properly

**Reproduction of the problem**
1-I forked the project
2-`npm install`
3-`npm start`
4-Got the following error:

function webpackConfig(options = {}) {
                               ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (C:\Users\Yann\Documents\swimlane\angular2-data-table\node_modules\webpack\bin\convert-argv.js:93:13)
    at Object.<anonymous> (C:\Users\Yann\Documents\swimlane\angular2-data-table\node_modules\webpack-dev-server\bin\webpack-dev-server.js:127:48)
    at Module._compile (module.js:409:26)

**Please tell us about your environment:**
Windows 10

* **Table version:** 
Master

* **Angular version:** 
2.0.2

**Comment by amcdnl** [comment]
What version of node are you using?

**Comment by yann510** [comment]
@amcdnl I'm using node `4.6.0` and npm `3.10.8`

**Comment by amcdnl** [comment]
Doesn't work on node 4.x
