### ISSUE TITLE
@angular/compiler v. 2.1.1 conflict with @angular/compiler-cli v. 0.6.4  causes ngc build fail

### ISSUE THREAD

**Issue by 2goatduo** [swimlane/angular2-data-table#224]
**I'm submitting a ...**  (check one with "x")

```
[X] report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
- `ngc`  build fails with error:

```
angular2-data-table/node_modules/@angular/compiler-cli/src/private_import_compiler.js:10
exports.AssetUrl = compiler_1.__compiler_private__.AssetUrl;
                                                  ^
TypeError: Cannot read property 'AssetUrl' of undefined
    at Object.<anonymous> (angular2-data-table/node_modules/@angular/compiler-cli/src/private_import_compiler.js:10:51)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (angular2-data-table/node_modules/@angular/compiler-cli/src/reflector_host.js:13:33)
    at Module._compile (module.js:556:32)
```

**Expected behavior**
@angular/compiler-cli requires @angular/compiler and expects it to export `__compiler_private__`, but v.2.1.1 of @angular/compiler doesn't.

**Reproduction of the problem**
- git clone
- `./node_modules/.bin/ngc -p tsconfig.aot.json`

**What is the motivation / use case for changing the behavior?**
Aot build of project depending on angular2-data-table needs .metadata.json files produced by ngc build of angular2-data-table.  `tsc` and `ngc` do NOT produce same .metadata.json files.

**Please tell us about your environment:**
- **Table version:** 0.11.2
  
  
- **Angular version:** 2.x.x
  
  
- **Browser:** n/a
  
  
- **Language:** n/a

**Comment by 2goatduo** [comment]
Rolling back @angular/compiler to v. 2.0.x fixes the bug.

**Comment by amcdnl** [comment]
AoT isn't supported yet. Once that hits, this will probably be fixed.

**Comment by amcdnl** [comment]
AoT is built in latest.
